Vagrant.configure("2") do |config|
    # Define web01 VM
    config.vm.define "web01" do |web01|
      web01.vm.box = "ubuntu/focal64" # Ubuntu 20.04 box
      web01.vm.hostname = "web01"     # Set hostname
      web01.vm.network "private_network", ip: "192.168.56.13" # Private IP
    end
  
    # Define web02 VM
    config.vm.define "web02" do |web02|
      web02.vm.box = "ubuntu/focal64" # Ubuntu 20.04 box
      web02.vm.hostname = "web02"     # Set hostname
      web02.vm.network "private_network", ip: "192.168.56.30" # Private IP
    end
  
    # Define db01 VM
    config.vm.define "db01" do |db01|
      db01.vm.box = "centos/7"   # CentOS 9 box
      db01.vm.hostname = "db01"  # Set hostname
      db01.vm.network "private_network", ip: "192.168.56.19" # Private IP
  
      # Provisioning for db01 using shell script
      db01.vm.provision "shell", inline: <<-SHELL
        yum install -y wget unzip mariadb-server -y
        systemctl start mariadb
        systemctl enable mariadb
    SHELL
    end
  end
  